server:
  port: 8080

spring:
  application:
    name: blog-yourssu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourssu_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: aug08aug08!

  jpa:
    database: mysql # ?????? ??? mysql? ??
    show-sql: false
    hibernate.ddl-auto: update # ddl-auto ??? MySQL ???? "update"? ???? ?? ???? ???? ????
    properties:
      hibernate:
        format_sql: true # SQL ?? ???

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
